### ISSUE TITLE
[ExceptionRender] Exceptions without $this->error still set the exceptions array when rendered

### ISSUE THREAD

**Issue by jamisonbryant** [mixerapi/mixerapi-dev#131]
**What Happened**
First off, not sure if this is an actual defect or if I'm throwing exceptions incorrectly. Feel free to let me know if it's the latter.

My tests broke as of Mixer 1.1.6 and I noticed the bugfix (#128) involving the `$exceptions` property in the exceptions renderer, here is the specific test failure I'm encountering:
```
 ✘ Authenticate rejects invalid base 64 encoded payloads
   ┐
   ├ Failed asserting that two strings are equal.
   ┊ ---·Expected
   ┊ +++·Actual
   ┊ @@ @@
   ┊ -'{"exception":"BadRequestException","message":"<error message>","url":"\/users\/authenticate","code":400}'
   ┊ +'{"exception":"BadRequestException","message":"<error message>","url":"\/users\/authenticate","code":400,"exceptions":[{}]}'
   │
   ╵ /Users/path/to/my/Code/tests/TestCase/Controller/UsersControllerTest.php:165
   ┴
```

Note the EMPTY `exceptions` property in the rendered exception. Here's the test that throws this error:
```php
$this->assertEquals(400, $this->_response->getStatusCode());
$expected = [
    'exception' => 'BadRequestException',
    'message' => AuthzError::REQUEST_AUTHORIZATION_HEADER_PAYLOAD_FAIL
    'url' => '/users/authenticate',
    'code' => 400,
    // 'exceptions' => [new stdClass()],          <-----  if I don't have this line, test fails
];
$expected = json_encode($expected);
$this->assertEquals($expected, (string) $this->_response->getBody());
```

See how I have to have the `exceptions` key in my array, with its value set to an array of a single stdClass object? That's yucky, no? It certainly feels very hacky to me. So I started tracking down where it could have come from.

It turns out that the exception getting rendered doesn't have the `$this->error` property set (unknown why) and so these lines (in the MixerApiExceptionRender):
```
$exceptions = [$exception];               // this is the offending line
$previous = $exception->getPrevious();
while ($previous != null) {
    $exceptions[] = $previous;
    $previous = $previous->getPrevious();
}
```

are resulting in an array with a single null entry, which gets encoded to the weird JSON as shown above.

**Expected Behavior**
I feel like the way it should behave is to do a null check on `$this->error` and set `$exceptions = [];` if it is null.

**Steps to Reproduce**
I'm just throwing basic exceptions from my controller like this, but as I mentioned above this could be wrong:
```
throw new BadRequestException(
    AuthzError::REQUEST_AUTHORIZATION_HEADER_REQUIRES_BASIC_SCHEME->description(true)
);
```

One other solution I considered was wrapping the Cake exceptions in my own custom exceptions which make sure to set `$this->error` but it also seems like a null check would be beneficial here.

**Version and Platform (please complete the following information):**
- OS/Platform: macOS
- CakePHP: 4.4.8
- MixerApi Version: 1.1.6

**Attachments**
N/A

**Comment by cnizzardini** [comment]
Hmm... I looked at this again and this indeed not intended behavior.

**Comment by cnizzardini** [comment]
So these changes introduced in 1.1.6 were meant to compensate for a change cakephp made in 4.4.6. Take a look at the changes introduced in WebExceptionRender and the related templates such as `https://github.com/cakephp/cakephp/compare/4.4.5...4.4.6` here: https://github.com/cakephp/cakephp/compare/4.4.5...4.4.6

This change caused issues in MixerAPI 1.1.5 and earlier. It appears I didn't compensate for them well. Unfortunately, as best I can tell, the `exceptions` property is now required.  Removing it causes issues for error rendering of standard text/html requests when debug is enabled.

** Long Term**

Exception Rendering needs to be re-thought, especially given all the other changes CakePHP has made with ErrorTraps. What MixerAPI has now will almost certainly go away with mixerapi v2 which will only support cakephp 5. In the interim I think a minor version should mark MixerApiExceptionRender::class as deprecated and instruct users to use whatever its replacement is.

** For Now**

Best I can think of to do is unset the `exceptions` property when debug is off which __doesn't seem__ to cause any issues. I am leaning towards this because that data should never be displayed in production applications. This was already done with the `errors` property.

**Comment by jamisonbryant** [comment]
Testing for just the code and the error string is definitely acceptable, thanks for that suggestion.

After a little more experimentation, the `$exceptions` var is _not_ in fact null on line 87 as I had previously thought. So I'm wondering now if the serialization is in fact what is causing the weird `[{}]` JSON. I think figuring out the exact problem there does in fact involve delving deep into the `WebExceptionRenderer` which I'm a bit hesitant to do for all the reasons you stated vis a vis the recent ErrorTrap changes and Cake 5.

I have confirmed via a local vendor file change that adding an `unset($viewVars['exceptions'])` to the debugViewVars() method resolves the problem by removing the problematic key entirely. I can put together a PR for this but might need a little help with the tests if that's OK.

**Comment by cnizzardini** [comment]
https://github.com/mixerapi/mixerapi-dev/releases/tag/v1.1.7
